version: '3.8'


services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/app'
      - './php.ini:/usr/local/etc/php/php.ini'
    ports:
      - "9000:9000" # php-fpm. for apcu
